export const bookThoughts = [
  { id: 1, author: "Stephen King", text: "Books are a uniquely portable magic." },
  { id: 2, author: "Unknown", text: "A library card is a passport to countless adventures." },
  { id: 3, author: "Dr. Seuss", text: "The more that you read, the more things you will know." },
  { id: 4, author: "Charles W. Eliot", text: "Books are the quietest and most constant of friends." },
  { id: 5, author: "George R.R. Martin", text: "A reader lives a thousand lives before he dies." },
  { id: 6, author: "Nelson Mandela", text: "Education is the most powerful weapon you can use to change the world." },
  { id: 7, author: "Unknown", text: "Libraries are treasure troves of knowledge." },
  { id: 8, author: "Unknown", text: "Every book is a journey waiting to be taken." },
  { id: 9, author: "Unknown", text: "Reading is dreaming with open eyes." },
  { id: 10, author: "Jorge Luis Borges", text: "I have always imagined that Paradise will be a kind of library." },
  { id: 11, author: "Unknown", text: "A library is a sanctuary of learning." },
  { id: 12, author: "Unknown", text: "Books teach us about the past to guide us in the future." },
  { id: 13, author: "Carl Sagan", text: "A book is proof that humans are capable of working magic." },
  { id: 14, author: "Unknown", text: "Libraries are where ideas are born." },
  { id: 15, author: "Oscar Wilde", text: "It is what you read when you don't have to that determines what you will be when you can't help it." },
  { id: 16, author: "Unknown", text: "A book in hand is a world in your grasp." },
  { id: 17, author: "Unknown", text: "Libraries nurture the seeds of knowledge." },
  { id: 18, author: "Mark Twain", text: "The man who does not read good books has no advantage over the man who cannot read them." },
  { id: 19, author: "Unknown", text: "Books inspire us to be better versions of ourselves." },
  { id: 20, author: "Albert Einstein", text: "The only thing that you absolutely have to know, is the location of the library." },
  { id: 21, author: "Unknown", text: "Books remind us of the beauty in life." },
  { id: 22, author: "Unknown", text: "A library visit is always time well spent." },
  { id: 23, author: "Unknown", text: "Books are timeless treasures." },
  { id: 24, author: "Unknown", text: "Libraries protect freedom of thought." },
  { id: 25, author: "Neil Gaiman", text: "A library is a place that is a repository of information and gives every citizen equal access to it." },
  { id: 26, author: "Unknown", text: "Reading makes the impossible seem possible." },
  { id: 27, author: "Unknown", text: "Libraries light the way to knowledge." },
  { id: 28, author: "Unknown", text: "Books build bridges between people and ideas." },
  { id: 29, author: "Unknown", text: "A book can transport you anywhere in the universe." },
  { id: 30, author: "Malala Yousafzai", text: "Let us remember: One book, one pen, one child, and one teacher can change the world." },
  { id: 31, author: "Unknown", text: "Books challenge us to think deeply." },
  { id: 32, author: "Unknown", text: "Libraries foster community and connection." },
  { id: 33, author: "Unknown", text: "Books inspire action and change." },
  { id: 34, author: "Unknown", text: "Libraries are the backbone of a literate society." },
  { id: 35, author: "Unknown", text: "Books spark revolutions of the mind." },
  { id: 36, author: "Unknown", text: "Libraries make learning accessible to all." },
  { id: 37, author: "Unknown", text: "Books give us the courage to dream." },
  { id: 38, author: "Unknown", text: "Reading sharpens the tools of thought." },
  { id: 39, author: "Unknown", text: "Books connect us to other cultures and perspectives." },
  { id: 40, author: "Unknown", text: "Libraries empower individuals with knowledge." },
  { id: 41, author: "Maya Angelou", text: "Any book that helps a child to form a habit of reading, to make reading one of his deep and continuing needs, is good for him." },
  { id: 42, author: "Haruki Murakami", text: "If you only read the books that everyone else is reading, you can only think what everyone else is thinking." },
  { id: 43, author: "Margaret Fuller", text: "Today a reader, tomorrow a leader." },
  { id: 44, author: "Unknown", text: "Books are lighthouses in the sea of time." },
  { id: 45, author: "C.S. Lewis", text: "A children's story that can only be enjoyed by children is not a good children's story in the slightest." },
  { id: 46, author: "Unknown", text: "Libraries are sanctuaries of self-discovery." },
  { id: 47, author: "Virginia Woolf", text: "Books are the mirrors of the soul." },
  { id: 48, author: "Unknown", text: "Every page turned is a new adventure begun." },
  { id: 49, author: "Ralph Waldo Emerson", text: "In the highest civilization, the book is still the highest delight." },
  { id: 50, author: "Unknown", text: "Libraries hold the stories of humanity." },
  { id: 51, author: "Toni Morrison", text: "Books are a form of political action. Books are knowledge. Books are reflection. Books change your mind." },
  { id: 52, author: "Unknown", text: "Every library shelf tells a thousand stories." },
  { id: 53, author: "Jane Austen", text: "I declare after all there is no enjoyment like reading!" },
  { id: 54, author: "Unknown", text: "Libraries are portals to infinite possibilities." },
  { id: 55, author: "Franz Kafka", text: "A book must be the axe for the frozen sea within us." },
  { id: 56, author: "Unknown", text: "Reading is the key to unlocking your potential." },
  { id: 57, author: "Roald Dahl", text: "If you are going to get anywhere in life you have to read a lot of books." },
  { id: 58, author: "Unknown", text: "Libraries are gardens of the mind." },
  { id: 59, author: "Ernest Hemingway", text: "There is no friend as loyal as a book." },
  { id: 60, author: "Unknown", text: "Books are windows to different worlds." },
  { id: 61, author: "Ray Bradbury", text: "You don't have to burn books to destroy a culture. Just get people to stop reading them." },
  { id: 62, author: "Unknown", text: "Libraries are the cornerstone of democracy." },
  { id: 63, author: "Umberto Eco", text: "The book is like the spoon: once invented, it cannot be bettered." },
  { id: 64, author: "Unknown", text: "Every book has a soul of its own." },
  { id: 65, author: "William Nicholson", text: "We read to know we're not alone." },
  { id: 66, author: "Unknown", text: "Libraries are time machines." },
  { id: 67, author: "Marcus Tullius Cicero", text: "A room without books is like a body without a soul." },
  { id: 68, author: "Unknown", text: "Reading gives us someplace to go when we have to stay where we are." },
  { id: 69, author: "Doris Lessing", text: "With a library you are free, not confined by temporary political climates." },
  { id: 70, author: "Unknown", text: "Books are the compasses that lead us forward." },
  { id: 71, author: "Walter Savage Landor", text: "What is reading but silent conversation?" },
  { id: 72, author: "Unknown", text: "Libraries are temples of learning." },
  { id: 73, author: "Mortimer J. Adler", text: "Reading is a basic tool in the living of a good life." },
  { id: 74, author: "Unknown", text: "Every book is a new beginning." },
  { id: 75, author: "Groucho Marx", text: "Outside of a dog, a book is man's best friend. Inside of a dog, it's too dark to read." },
  { id: 76, author: "Unknown", text: "Libraries are bridges to better futures." },
  { id: 77, author: "Helen Hayes", text: "From your parents you learn love and laughter and how to put one foot in front of the other. But when books are opened, you discover you have wings." },
  { id: 78, author: "Unknown", text: "Reading is breathing for the mind." },
  { id: 79, author: "Aldous Huxley", text: "Every man who knows how to read has it in his power to magnify himself." },
  { id: 80, author: "Unknown", text: "Libraries are the universities of the people." },
  { id: 81, author: "Unknown", text: "Books are the seeds of change." },
  { id: 82, author: "Diane Duane", text: "Reading one book is like eating one potato chip." },
  { id: 83, author: "Unknown", text: "Libraries hold the keys to understanding." },
  { id: 84, author: "Unknown", text: "Books are the foundation of civilization." },
  { id: 85, author: "Arthur Conan Doyle", text: "The world is full of obvious things which nobody by any chance ever observes." },
  { id: 86, author: "Unknown", text: "Reading expands the boundaries of possibility." },
  { id: 87, author: "Unknown", text: "Libraries are lighthouses for the mind." },
  { id: 88, author: "Louisa May Alcott", text: "Some books are so familiar that reading them is like being home again." },
  { id: 89, author: "Unknown", text: "Every page turned is wisdom earned." },
  { id: 90, author: "Unknown", text: "Libraries preserve our cultural heritage." },
  { id: 91, author: "Unknown", text: "Books are the building blocks of understanding." },
  { id: 92, author: "Anne Herbert", text: "Libraries will get you through times of no money better than money will get you through times of no libraries." },
  { id: 93, author: "Unknown", text: "Reading is the road to enlightenment." },
  { id: 94, author: "Unknown", text: "Books are silent mentors." },
  { id: 95, author: "Unknown", text: "Libraries are sanctuaries of hope." },
  { id: 96, author: "Ursula K. Le Guin", text: "We read books to find out who we are." },
  { id: 97, author: "Unknown", text: "Every book has the power to transform." },
  { id: 98, author: "Unknown", text: "Libraries are the heartbeat of communities." },
  { id: 99, author: "Unknown", text: "Books are the footprints of great minds." },
  { id: 100, author: "Unknown", text: "Reading is the foundation of learning." },
  { id: 101, author: "Unknown", text: "Libraries are gardens where ideas grow." },
  { id: 102, author: "Unknown", text: "Books are the maps to understanding ourselves." },
  { id: 103, author: "Unknown", text: "Reading opens doors to new perspectives." },
  { id: 104, author: "Unknown", text: "Libraries are bridges to knowledge." },
  { id: 105, author: "Unknown", text: "Books are the echoes of wisdom." },
  { id: 106, author: "Unknown", text: "Reading illuminates the path forward." },
  { id: 107, author: "Unknown", text: "Libraries are the pillars of education." },
  { id: 108, author: "Unknown", text: "Books are the keys to imagination." },
  { id: 109, author: "Unknown", text: "Reading shapes our understanding." },
  { id: 110, author: "Unknown", text: "Libraries are beacons of wisdom." },
  { id: 111, author: "Unknown", text: "Books are the vessels of knowledge." },
  { id: 112, author: "Unknown", text: "Reading broadens horizons." },
  { id: 113, author: "Unknown", text: "Libraries are the guardians of truth." },
  { id: 114, author: "Unknown", text: "Books are the bridges to understanding." },
  { id: 115, author: "Unknown", text: "Reading cultivates empathy." },
  { id: 116, author: "Unknown", text: "Libraries are the foundations of learning." },
  { id: 117, author: "Unknown", text: "Books are the seeds of wisdom." },
  { id: 118, author: "Unknown", text: "Reading nurtures the soul." },
  { id: 119, author: "Unknown", text: "Libraries are the keepers of stories." },
  { id: 120, author: "Unknown", text: "Books are the pathways to knowledge." },
  { id: 121, author: "Unknown", text: "Reading enriches the mind." },
  { id: 122, author: "Unknown", text: "Libraries are the archives of human thought." },
  { id: 123, author: "Unknown", text: "Books are the windows to wisdom." },
  { id: 124, author: "Unknown", text: "Reading transforms perspectives." },
  { id: 125, author: "Unknown", text: "Libraries are the custodians of knowledge." },
  { id: 126, author: "Unknown", text: "Books are the catalysts of change." },
  { id: 127, author: "Unknown", text: "Reading awakens possibilities." },
  { id: 128, author: "Unknown", text: "Libraries are the repositories of dreams." },
  { id: 129, author: "Unknown", text: "Books are the bridges to tomorrow." },
  { id: 130, author: "Unknown", text: "Reading ignites imagination." },
  { id: 131, author: "Unknown", text: "Libraries are the foundations of democracy." },
  { id: 132, author: "Unknown", text: "Books are the vessels of dreams." },
  { id: 133, author: "Unknown", text: "Reading opens new worlds." },
  { id: 134, author: "Unknown", text: "Libraries are the guardians of wisdom." },
  { id: 135, author: "Unknown", text: "Books are the keys to understanding." },
  { id: 136, author: "Unknown", text: "Reading builds character." },
  { id: 137, author: "Unknown", text: "Libraries are the temples of wisdom." },
  { id: 138, author: "Unknown", text: "Books are the foundations of growth." },
  { id: 139, author: "Unknown", text: "Reading shapes destiny." },
  { id: 140, author: "Unknown", text: "Libraries are the beacons of hope." },
  { id: 141, author: "Unknown", text: "Books are the stepping stones to success." },
  { id: 142, author: "Unknown", text: "Reading cultivates wisdom." },
  { id: 143, author: "Unknown", text: "Libraries are the pillars of civilization." },
  { id: 144, author: "Unknown", text: "Books are the seeds of innovation." },
  { id: 145, author: "Unknown", text: "Reading builds bridges." },
  { id: 146, author: "Unknown", text: "Libraries are the foundations of progress." },
  { id: 147, author: "Unknown", text: "Books are the vessels of time." },
  { id: 148, author: "Unknown", text: "Reading shapes the future." },
  { id: 149, author: "Unknown", text: "Libraries are the keepers of history." },
  { id: 150, author: "Unknown", text: "Books are the pathways to enlightenment." },
  { id: 151, author: "Unknown", text: "Reading transforms lives." },
  { id: 152, author: "Unknown", text: "Libraries are the cornerstones of learning." },
  { id: 153, author: "Unknown", text: "Books are the bridges to understanding." },
  { id: 154, author: "Unknown", text: "Reading illuminates truth." },
  { id: 155, author: "Unknown", text: "Libraries are the guardians of knowledge." },
  { id: 156, author: "Unknown", text: "Books are the keys to wisdom." },
  { id: 157, author: "Unknown", text: "Reading opens minds." },
  { id: 158, author: "Unknown", text: "Libraries are the foundations of culture." },
  { id: 159, author: "Unknown", text: "Books are the vessels of enlightenment." },
  { id: 160, author: "Unknown", text: "Reading builds understanding." },
  { id: 161, author: "Unknown", text: "Libraries are the keepers of wisdom." },
  { id: 162, author: "Unknown", text: "Books are the pathways to growth." },
  { id: 163, author: "Unknown", text: "Reading nurtures wisdom." },
  { id: 164, author: "Unknown", text: "Libraries are the bridges to tomorrow." },
  { id: 165, author: "Unknown", text: "Books are the foundations of knowledge." },
  { id: 166, author: "Unknown", text: "Reading shapes character." },
  { id: 167, author: "Unknown", text: "Libraries are the vessels of learning." },
  { id: 168, author: "Unknown", text: "Books are the keys to growth." },
  { id: 169, author: "Unknown", text: "Reading builds wisdom." },
  { id: 170, author: "Unknown", text: "Libraries are the pathways to understanding." },
  { id: 171, author: "Unknown", text: "Books are the bridges to knowledge." },
  { id: 172, author: "Unknown", text: "Reading shapes minds." },
  { id: 173, author: "Unknown", text: "Libraries are the foundations of wisdom." },
  { id: 174, author: "Unknown", text: "Books are the vessels of understanding." },
  { id: 175, author: "Unknown", text: "Reading builds knowledge." },
  { id: 176, author: "Unknown", text: "Libraries are the keys to enlightenment." },
  { id: 177, author: "Unknown", text: "Books are the pathways to wisdom." },
  { id: 178, author: "Unknown", text: "Reading shapes understanding." },
  { id: 179, author: "Unknown", text: "Libraries are the bridges to knowledge." },
  { id: 180, author: "Unknown", text: "Books are the foundations of enlightenment." },
  { id: 181, author: "Unknown", text: "Reading builds understanding." },
  { id: 182, author: "Unknown", text: "Libraries are the vessels of wisdom." },
  { id: 183, author: "Unknown", text: "Books are the keys to knowledge." },
  { id: 184, author: "Unknown", text: "Reading shapes wisdom." },
  { id: 185, author: "Unknown", text: "Libraries are the pathways to learning." },
  { id: 186, author: "Unknown", text: "Books are the bridges to enlightenment." },
  { id: 187, author: "Unknown", text: "Reading builds enlightenment." },
  { id: 188, author: "Unknown", text: "Libraries are the foundations of understanding." },
  { id: 189, author: "Unknown", text: "Books are the vessels of growth." },
  { id: 190, author: "Unknown", text: "Reading shapes knowledge." },
  { id: 191, author: "Unknown", text: "Libraries are the keys to wisdom." },
  { id: 192, author: "Unknown", text: "Books are the pathways to understanding." },
  { id: 193, author: "Unknown", text: "Reading builds growth." },
  { id: 194, author: "Unknown", text: "Libraries are the bridges to enlightenment." },
  { id: 195, author: "Unknown", text: "Books are the foundations of wisdom." },
  { id: 196, author: "Unknown", text: "Reading shapes enlightenment." },
  { id: 197, author: "Unknown", text: "Libraries are the vessels of knowledge." },
  { id: 198, author: "Unknown", text: "Books are bridges across generations." },
  { id: 199, author: "Unknown", text: "Libraries preserve the wisdom of ages." },
  { id: 200, author: "John Green", text: "Great books help you understand, and they help you feel understood." }
];


